name: thonny
base: core22
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny
 
apps:
  thonny:
    command: bin/thonny
    extensions: [gnome]
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
      TMPDIR: $XDG_RUNTIME_DIR
      PYTHONPATH: ${SNAP}/lib64/python3.10/site-packages:${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages:${SNAP}/usr/local/lib/python3.10/dist-packages:${SNAP}/usr/lib/python3.10
    common-id: org.thonny.Thonny
    desktop: utils/org.thonny.Thonny.desktop 
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - browser-support
      - bluez
      - camera
      - hardware-observe
      - system-observe
      - mount-observe
      - optical-drive
      - removable-media
      - raw-usb
      - unity7
      - screen-inhibit-control
      - udisks2
      - upower-observe
      
parts:
  thonny:
    plugin: python
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.2
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.11
      - -pyvenv.cfg
      - -lib/python3.10/site-packages/setuptools*
      - -lib/python3.10/site-packages/pip*
      - -share/python-wheels
      - -share/doc
      - -share/man
  
  utils: # For Using Upstream Desktop and Icon Files.
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.2
    after: [thonny]
    plugin: dump
    override-pull: |
      craftctl default
      sed -e 's|Exec=/usr/bin/thonny %F|Exec=bin/thonny %F|' -i packaging/linux/org.thonny.Thonny.desktop
      sed -e 's|Icon=thonny|Icon=${SNAP}/utils/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop
      mkdir utils
      cp packaging/linux/org.thonny.Thonny.desktop utils
      cp packaging/icons/thonny-256x256.png utils
    stage:
      - utils
         
  zenity: # For accessing gtk-file-portal by thonny.
    source: https://gitlab.gnome.org/GNOME/zenity.git
    source-tag: 3.44.1
    after: [utils]
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
    stage:
      - usr/bin
      - usr/share/zenity 
       
  sundry-deps: # For sundry reasons.
    after: [zenity]
    plugin: nil  
    stage-packages:
      - libnotify-bin
      - xclip
      - python3-tk
      - libxmu6
      - tk8.6-blt2.5
      - libtcl8.6
      - libtk8.6
      - libxss1
    prime:
      - usr/lib/python3.10/lib-dynload
      - usr/lib/python3.10/tkinter
      - usr/bin/notify*
      - usr/bin/xclip*
      - usr/lib/*/libXmu.so*
      - usr/lib/blt2.5
      - usr/lib/libBLT*
      - usr/lib/*/libtcl8.6.so*
      - usr/share/tcltk
      - usr/lib/*/libtk8.6.so*
      - usr/lib/tcltk
      - usr/lib/*/libXss.so*
       
  cleanup:
    after: [sundry-deps]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
 
