name: thonny
base: core18
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  
slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny
 
apps:
  thonny:
    command: bin/thonny
    extensions: [gnome-3-34]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - avahi-control
      - avahi-observe
      - bluetooth-control
      - camera
      - hardware-observe
      - system-observe
      - process-control
      - optical-drive
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      - udisks2
      - upower-observe
    desktop: packaging/linux/org.thonny.Thonny.desktop   

parts:
  thonny:
    source: https://github.com/thonny/thonny.git
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    plugin: dump
    build-packages:
      - wget
    stage-packages:
      - zenity  
    override-pull: |
      snapcraftctl default
      snapcraftctl set-version $(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      wget -q -O- https://github.com/thonny/thonny/releases/download/v${VER}/thonny-${VER}-x86_64.tar.gz |\
           tar xzf - --strip-components=1 -C $SNAPCRAFT_PART_SRC
    prime:
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libhistory.so*
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libtinfo.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_fs.so* 
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_loop.so* 
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_part.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_swap.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libformw.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmenuw.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtic.so*
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libparted-fs-resize.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_part_err.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpanelw.so*
 
  fatloss:
    after: [thonny]
    plugin: nil 
    override-prime: |
      snapcraftctl default
      rm -rf usr/share/locale
      rm -rf usr/share/help
      rm -rf usr/share/doc
      rm -rf usr/share/fonts
      rm -rf usr/share/man
      rm -rf include
      rm -rf packaging/mac
      rm -rf packaging/windows
      rm -rf packaging/setuptools
       
  cleanup:
    after: [fatloss]
    plugin: nil
    build-snaps: [core18, gtk-common-themes, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-34-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done    
 
