name: thonny
base: core18
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
   
slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny
 
apps:
  thonny:
    command: bin/thonny
    extensions: [gnome-3-34]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - camera
      - hardware-observe
      - system-observe
      - upower-observe
      - optical-drive
      - raw-usb
      - udisks2
      - removable-media
      - screen-inhibit-control
    desktop: packaging/linux/org.thonny.Thonny.desktop   

parts:
  thonny:
    source: https://github.com/thonny/thonny.git
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    plugin: dump
    build-packages:
      - wget
    override-pull: |
      snapcraftctl pull
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      wget -q -O- https://github.com/thonny/thonny/releases/download/v${VER}/thonny-${VER}-x86_64.tar.gz |\
           tar xzf - --strip-components=1 -C $SNAPCRAFT_PART_SRC
    override-prime: |
      snapcraftctl prime
      sed -e 's|Icon=thonny|Icon=${SNAP}/packaging/icons/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop 
    stage:
      - -packaging/setuptools
      - -packaging/mac
      - -packaging/windows
      - -include 
      - -thonny
      - -misc
      - -templates
      - -data
      - -docs
      - -licenses
      - -packaging/pip*
      - -packaging/portable*
      - -packaging/readme*
      - -packaging/requirements*
      - -packaging/icons/preview*
      - -packaging/license*
      - -packaging/linux/build*
      - -packaging/linux/install*
      - -packaging/linux/create*
      - -packaging/linux/insert*
      - -packaging/linux/downinstall*
      - -packaging/linux/uninstall*
      - -packaging/linux/readme*
      - -packaging/linux/README*
      - -packaging/linux/thonny*
      - -packaging/linux/Thonny*
      - -packaging/linux/org.thonny.Thonny.Devel.yaml
      - -build*
      - -copy*
      - -MANIFEST*
      - -CONTRIBUTING*
      - -requirements*
      - -README*
      - -LICENSE*
      - -CHANGELOG*
      - -mypy*
      - -pyproject*
      - -install*
      - -CREDITS*
      - -setup*         
      
  xclip: 
    after: [thonny] 
    source: https://github.com/astrand/xclip.git
    source-tag: '0.13'
    plugin: autotools
    configflags:
      - --prefix=/usr
    build-packages:
      - libxmu-dev
      - libxmu-headers 
    stage-packages:
      - libxmu6
      - libxt6   
    prime:
      - usr/bin
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libXt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libXmu.so*
     
  sundry-deps: 
    after: [xclip]
    plugin: nil  
    stage-packages:
      - libnotify-bin
      - zenity
    prime:
      - usr/bin
      - usr/share/zenity
       
  cleanup:
    after: [sundry-deps]
    plugin: nil
    build-snaps: [core18, gtk-common-themes, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-34-1804"; do
          cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done    
 
