name: thonny
base: core22
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny

apps:
  thonny:
    command: bin/thonny
    extensions: [gnome]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3.10/site-packages
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - camera
      - hardware-observe
      - system-observe
      - upower-observe
      - optical-drive
      - raw-usb
      - udisks2
      - removable-media
      - screen-inhibit-control
    desktop: utils/org.thonny.Thonny.desktop

parts:
  tcltk:
    plugin: nil
    source: .
    build-packages:
      - make
      - wget
    override-build: |
      craftctl default
      bash tcltk.sh
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/man
      - -usr/share/man

  thonny:
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.3
    after: [tcltk]
    plugin: python
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      - -share
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/python*
      - -bin/pip*
      - -include
      - -pyvenv.cfg
      - -lib/**/setuptools*
      - -lib/**/pip*

  utils:
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.3
    after: [thonny]
    plugin: dump
    override-pull: |
      craftctl default
      sed -e 's|Exec=/usr/bin/thonny %F|Exec=bin/thonny %F|' -i packaging/linux/org.thonny.Thonny.desktop
      sed -e 's|Icon=thonny|Icon=${SNAP}/utils/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop
      mkdir utils
      cp packaging/linux/org.thonny.Thonny.desktop utils
      cp packaging/icons/thonny-256x256.png utils
    prime:
      - utils

  deps:
    after: [utils]
    plugin: nil
    stage-packages:
      - libnotify-bin
      - zenity
      - xclip
    prime:
      - usr/bin
      - usr/lib

  cleanup:
    after: [deps]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
          cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
