name: thonny
base: core22
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-for: amd64
  - build-for: arm64
  - build-for: armhf

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny
 
apps:
  thonny:
    command: bin/thonny
    extensions: [gnome]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - avahi-control
      - avahi-observe
      - bluetooth-control
      - camera
      - hardware-observe
      - system-observe
      - process-control
      - optical-drive
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      - udisks2
      - upower-observe
    desktop: packaging/linux/org.thonny.Thonny.desktop   

parts:
  thonny:
    source: https://github.com/thonny/thonny.git
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    after: [zenity]
    plugin: dump
    build-packages:
      - wget
      - curl
      - build-essential
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      wget -q -O- https://github.com/thonny/thonny/releases/download/v${VER}/thonny-${VER}-x86_64.tar.gz |\
           tar xzf - --strip-components=1 -C $CRAFT_PART_SRC
    stage-packages:
      - libncursesw5
      - libtinfo5
      - libgdbm6
      - libreadline8
      - libffi8
      - libfreetype6
      - libfontconfig1
      - libpng16-16
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxft2
      - libxrender1
      - udisks2
      - python3-dbus
    prime:
      - -lib/$CRAFT_ARCH_TRIPLET/libhistory.so*
      - -lib/$CRAFT_ARCH_TRIPLET/libtinfo.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libbd_fs.so* 
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libbd_loop.so* 
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libbd_part.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libbd_swap.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libformw.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libmenuw.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libtic.so*
      - -lib/$CRAFT_ARCH_TRIPLET/libparted-fs-resize.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libbd_part_err.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libpanelw.so*
  zenity:
    source: https://gitlab.gnome.org/GNOME/zenity.git
    source-tag: 3.44.1
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
    build-packages:
      - build-essential
  
  cleanup:
    after: [thonny]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
 
