name: thonny
base: core18
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny

apps:
  thonny:
    command: bin/thonny
    extensions: [gnome-3-34]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
      PYTHONPATH: ${SNAP}/lib/python3.9/site-packages:${SNAP}/usr/lib/python3.9/site-packages
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - camera
      - hardware-observe
      - system-observe
      - upower-observe
      - optical-drive
      - raw-usb
      - udisks2
      - removable-media
      - screen-inhibit-control
    desktop: utils/org.thonny.Thonny.desktop

parts:
  tcltk:
    plugin: nil
    source: .
    build-packages:
      - make
      - wget
    override-build: |
      snapcraftctl build
      bash tcltk.sh
    prime:
      - -usr/include
      - -usr/lib/pkgconfig  
      - -usr/man
      - -usr/share/man
      
  python:
    source: https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tar.xz
    source-checksum: md5/765576c3af57deb046819ecd57804bbb
    after: [tcltk]
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --with-ensurepip=install
      - --enable-optimizations
    build-packages:
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libbz2-dev 
      - lzma-dev 
      - liblzma-dev 
      - xz-utils
      - uuid-dev 
      - libffi-dev 
      - tk-dev
      - nasm
    prime:
      - -usr/include
      - -usr/lib/libpython3.9*
      - -usr/lib/pkgconfig
      - -usr/share/man
      - -usr/lib/*/test
      - -usr/lib/*/idlelib
      - -usr/lib/*/lib2to3
      - -usr/lib/*/config-3.9-$SNAPCRAFT_ARCH_TRIPLET/libpython3.9*
      - -usr/lib/*/config-3.9-$SNAPCRAFT_ARCH_TRIPLET/python.o
      - -usr/bin/2to3*
      - -usr/bin/idle*
      - -usr/bin/pydoc*

  thonny:
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.2
    after: [python]
    plugin: python
    python-packages:
      - pylint == 2.17.5
      - jedi == 0.19.0
      - pyserial == 3.5
      - mypy == 1.5.1
      - docutils == 0.20.1
      - Send2Trash == 1.8.2
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
   
  utils:
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.2
    after: [thonny]
    plugin: dump
    override-pull: |
      snapcraftctl pull
      sed -e 's|Exec=/usr/bin/thonny %F|Exec=bin/thonny %F|' -i packaging/linux/org.thonny.Thonny.desktop
      sed -e 's|Icon=thonny|Icon=${SNAP}/utils/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop
      mkdir utils
      cp packaging/linux/org.thonny.Thonny.desktop utils
      cp packaging/icons/thonny-256x256.png utils
    prime:
      - utils

  xclip:
    after: [utils]
    source: https://github.com/astrand/xclip/archive/refs/tags/0.13.tar.gz
    plugin: autotools
    configflags:
      - --prefix=/usr
    build-packages:
      - libxmu-dev
      - libxmu-headers
    stage-packages:
      - libxmu6
      - libxt6
    prime:
      - usr/bin
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libXt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libXmu.so*

  deps:
    after: [xclip]
    plugin: nil
    stage-packages:
      - libnotify-bin
      - zenity
    prime:
      - usr/bin/zenity
      - usr/bin/gdialog
      - usr/bin/notify-send
      - usr/share/zenity

  cleanup:
    after: [deps]
    plugin: nil
    build-snaps: [core18, gtk-common-themes, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-34-1804"; do
          cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
