name: thonny
base: core18
adopt-info: thonny
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny
 
apps:
  thonny:
    command: bin/thonny
    extensions: [gnome-3-34]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - avahi-control
      - avahi-observe
      - bluetooth-control
      - camera
      - hardware-observe
      - system-observe
      - process-control
      - optical-drive
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      - udisks2
      - upower-observe
    desktop: packaging/linux/org.thonny.Thonny.desktop   

parts:
  thonny:
    source: https://github.com/thonny/thonny.git
    parse-info: [packaging/linux/org.thonny.Thonny.appdata.xml]
    plugin: dump
    build-packages:
      - wget
    override-pull: |
      snapcraftctl pull
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      wget -q -O- https://github.com/thonny/thonny/releases/download/v${VER}/thonny-${VER}-x86_64.tar.gz |\
           tar xzf - --strip-components=1 -C $SNAPCRAFT_PART_SRC
    override-prime: |
      snapcraftctl prime
      sed -e 's|Icon=thonny|Icon=${SNAP}/packaging/icons/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop         
    prime:
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libhistory.so*
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libtinfo.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_fs.so* 
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_loop.so* 
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_part.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_swap.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libformw.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmenuw.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtic.so*
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libparted-fs-resize.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libbd_part_err.so*
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpanelw.so*
    
  zenity:
    after: [thonny]
    source: https://gitlab.gnome.org/GNOME/zenity.git
    source-tag: 3.41.0
    plugin: meson
    meson-version: 0.61.5
    meson-parameters:
      - -Dprefix=/usr
      
  fatloss:
    after: [zenity]
    plugin: nil 
    override-prime: |
      snapcraftctl prime
      rm -rf usr/share/locale
      rm -rf usr/share/help
      rm -rf usr/share/doc
      rm -rf usr/share/fonts
      rm -rf usr/share/man
      rm -rf include
      rm -rf packaging/mac
      rm -rf packaging/windows
      rm -rf packaging/setuptools
       
  cleanup:
    after: [fatloss]
    plugin: nil
    build-snaps: [core18, gtk-common-themes, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-34-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done    
 
