name: thonny
base: core22
adopt-info: appinfo
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  thonny:
    interface: dbus
    bus: session
    name: org.thonny.Thonny

apps:
  thonny:
    command: usr/local/bin/thonny
    extensions: [gnome]
    common-id: org.thonny.Thonny
    environment:
      THONNY_USER_DIR: $SNAP_USER_DATA
      TMPDIR: $XDG_RUNTIME_DIR
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3.10/site-packages:${SNAP}/usr/local/lib/python3.10/dist-packages
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-playback
      - audio-record
      - bluez
      - camera
      - hardware-observe
      - system-observe
      - upower-observe
      - optical-drive
      - raw-usb
      - udisks2
      - removable-media
      - screen-inhibit-control
    desktop: appinfo/org.thonny.Thonny.desktop

parts:
  thonny:
    plugin: nil
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr thonny==4.1.4

  appinfo:
    source: https://github.com/thonny/thonny.git
    source-tag: v4.1.4
    after: [thonny]
    parse-info: [thonny/packaging/linux/org.thonny.Thonny.appdata.xml]
    plugin: dump
    override-pull: |
      craftctl default
      sed -e 's|Exec=/usr/bin/thonny %F|Exec=usr/local/bin/thonny %F|' -i packaging/linux/org.thonny.Thonny.desktop
      sed -e 's|Icon=thonny|Icon=${SNAP}/appinfo/thonny-256x256.png|' -i packaging/linux/org.thonny.Thonny.desktop
      mkdir appinfo
      cp packaging/linux/org.thonny.Thonny.desktop appinfo
      cp packaging/icons/thonny-256x256.png appinfo
    prime:
      - appinfo

  tkinter:
    after: [appinfo]
    plugin: nil
    stage-packages:
      - python3-tk

  deps:
    after: [tkinter]
    plugin: nil
    stage-packages:
      - libnotify-bin
      - zenity
      - xclip
    prime:
      - usr/bin/xclip*
      - usr/bin/zenity
      - usr/bin/notify-send
      - usr/lib/*/libXt.so*
      - usr/lib/*/libXmu.so*
      - usr/share/zenity
